directory: /music/beets-in
library: /home/vagrant/beets/library.db

import:
  move: yes
  write: yes
  copy: no

paths:
  default: $albumartist - $album%aunique{}/$track -  $albumartist - $title
copyartifacts:
  extensions: .log .jpg .png
  print_ignored: yes

plugins: fetchart lastgenre embedart discogs
